---

# Ansible Requirements File
# https://docs.ansible.com/ansible/galaxy.html#advanced-control-over-role-requirements-files
#
# Install via: ansible-galaxy install -r requirements.yml

- src: sebalix.odoo
  version: 1.1.0

- src: ANXS.postgresql
  version: v1.5.0

- src: geerlingguy.nginx
  version: 1.9.0

- src: HanXHX.firewall

- src: tersmitten.postfix
  version: v1.5.0
