---

# Ansible Requirements File
# https://docs.ansible.com/ansible/galaxy.html#advanced-control-over-role-requirements-files
#
# Install via: ansible-galaxy install -r requirements.yml

- src: sebalix.odoo
  version: 1.1.0

- src: ANXS.postgresql
  version: v1.5.0
